#==================
#     GENERAL
#==================
# General informations to the plugin work

name: Souls
api: [4.0.0]
version: 1.1.0
main: Henry8K\Souls\Main

#==================
#      OTHER
#==================
# Additional informations about the plugin

author: ["Henry8K"]
description: "A plugin that implements a Soul system for minecraft bedrock edition."