# ========================
#   GENERAL INFORMATIONS
# ========================

name: Souls
api: [4.0.0]
version: 1.0.0
main: Henry8K\Souls\Main

# ========================
#    OTHER INFORMATIONS
# ========================

author: ["Henry8K"]
softdepend: ["EconomyAPI",  "BedrockEconomy"]
description: "A plugin to implement the soul system on your server"

# ========================
#   GENERAL PERMISSIONS
# ========================

permissions:
    souls.view.command:
      description: "view souls command permission"
      default: true

    souls.sell.command:
      description: "sell souls command permission"
      default: true