# ========================
#   GENERAL INFORMATIONS
# ========================

name: Souls
api: [4.0.0]
version: 1.0.0
main: Henry8K\Souls\Main

# ========================
#    OTHER INFORMATIONS
# ========================

author: "Henry8K"
website: "https://henry8k.github.io/"
softdepend: ["EconomyAPI",  "BedrockEconomy"]
description: 'A plugin to implement souls system in your server'

# ========================
#   GENERAL PERMISSIONS
# ========================

permissions:
    souls.view.command:
      description: "View souls command permission"
      default: true

    souls.sell.command:
      description: "Sell souls command permission"
      default: true

    souls.manage.command:
      description: "Player souls manage command permission"
      default: op